### ISSUE TITLE
Update to 3.1.64-86 from upstream

### ISSUE THREAD

**Issue by garcia-jj** [webjars/jquery.inputmask#1]
There is a new version available.

https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/package.json

**Comment by jamesward** [comment]
That version doesn't exist as a tagged release: https://github.com/RobinHerbots/jquery.inputmask/tags

**Comment by garcia-jj** [comment]
My bad, sorry. Thanks for your support, @jamesward.
